query postConnection(
  $filterWord: TextFilterCondition
  $pageCondition: PageCondition
  $edgeOrder: EdgeOrder
) {
  postConnection(
    filterWord: $filterWord
    pageCondition: $pageCondition
    edgeOrder: $edgeOrder
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        post_date
        post_title
        post_content
        category {
          name
        }
        tags {
          name
        }
      }
      cursor
    }
    totalCount
  }
}