// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID           string `json:"id"`
	PostDate     string `json:"post_date"`
	PostContent  string `json:"post_content"`
	PostTitle    string `json:"post_title"`
	PostExcerpt  string `json:"post_excerpt"`
	PostModified string `json:"post_modified"`
}
